name: CD

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      target:
        description: "Target de deploy (dev, staging, prod)"
        required: true
        default: "staging"

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.target || 'staging' }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Databricks CLI
        uses: databricks/setup-cli@main

      - name: Deploy bundle
        run: databricks bundle deploy -t ${{ github.event.inputs.target || 'staging' }}
        env:
          DATABRICKS_HOST: ${{ secrets.DATABRICKS_HOST }}
          DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
